config/routes.rb
Predictor::Application.routes.draw do
  get "pages/home"

  get "pages/contact"

  resources :fixtures

  resources :users

  resources :teams

end

app/models/fixture.rb
class Fixture < ActiveRecord::Base
	has_many :teams
end

app/models/team.rb
class Team < ActiveRecord::Base
	belongs_to :fixture
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fixtures_controller.rb
class FixturesController < ApplicationController
  # GET /fixtures
  # GET /fixtures.xml
  def index
    @fixtures = Fixture.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @fixtures }
    end
  end

  # GET /fixtures/1
  # GET /fixtures/1.xml
  def show
    @fixture = Fixture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @fixture }
    end
  end

  # GET /fixtures/new
  # GET /fixtures/new.xml
  def new
    @fixture = Fixture.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @fixture }
    end
  end

  # GET /fixtures/1/edit
  def edit
    @fixture = Fixture.find(params[:id])
  end

  # POST /fixtures
  # POST /fixtures.xml
  def create
    @fixture = Fixture.new(params[:fixture])

    respond_to do |format|
      if @fixture.save
        format.html { redirect_to(@fixture, :notice => 'Fixture was successfully created.') }
        format.xml  { render :xml => @fixture, :status => :created, :location => @fixture }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @fixture.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /fixtures/1
  # PUT /fixtures/1.xml
  def update
    @fixture = Fixture.find(params[:id])

    respond_to do |format|
      if @fixture.update_attributes(params[:fixture])
        format.html { redirect_to(@fixture, :notice => 'Fixture was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @fixture.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /fixtures/1
  # DELETE /fixtures/1.xml
  def destroy
    @fixture = Fixture.find(params[:id])
    @fixture.destroy

    respond_to do |format|
      format.html { redirect_to(fixtures_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  # GET /teams
  # GET /teams.xml
  def index
    @teams = Team.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @teams }
    end
  end

  # GET /teams/1
  # GET /teams/1.xml
  def show
    @team = Team.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @team }
    end
  end

  # GET /teams/new
  # GET /teams/new.xml
  def new
    @team = Team.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @team }
    end
  end

  # GET /teams/1/edit
  def edit
    @team = Team.find(params[:id])
  end

  # POST /teams
  # POST /teams.xml
  def create
    @team = Team.new(params[:team])

    respond_to do |format|
      if @team.save
        format.html { redirect_to(@team, :notice => 'Team was successfully created.') }
        format.xml  { render :xml => @team, :status => :created, :location => @team }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @team.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /teams/1
  # PUT /teams/1.xml
  def update
    @team = Team.find(params[:id])

    respond_to do |format|
      if @team.update_attributes(params[:team])
        format.html { redirect_to(@team, :notice => 'Team was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @team.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.xml
  def destroy
    @team = Team.find(params[:id])
    @team.destroy

    respond_to do |format|
      format.html { redirect_to(teams_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fixtures_helper.rb
module FixturesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fixtures/_form.html.erb
<%= form_for(@fixture) do |f| %>
  <% if @fixture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fixture.errors.count, "error") %> prohibited this fixture from being saved:</h2>

      <ul>
      <% @fixture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date, :order => [:day, :month, :year] %>
  </div>
  <div class="field">
    <%= f.label :home_team %><br />
	<% teams = Team.all %>
	<%= f.collection_select :home_team, Team.all, :name, :name, :include_blank=>"-Please Select Home Team-" %>
  </div>
  <div class="field">
    <%= f.label :away_team %><br />
    <%= f.collection_select :away_team, Team.all, :name, :name, :include_blank=>"-Please Select Away Team-" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fixtures/edit.html.erb
<h1>Editing fixture</h1>

<%= render 'form' %>

<%= link_to 'Show', @fixture %> |
<%= link_to 'Back', fixtures_path %>

app/views/fixtures/index.html.erb
<h1>Listing fixtures</h1>

<table>
  <tr>
    <th>Date</th>
	<th>Kick Off</th>
    <th>Home team</th>
    <th>Away team</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fixtures.each do |fixture| %>
  <tr>
    <td><%= fixture.date.strftime("%d/%m/%Y") %></td>
	<td><%= fixture.date.strftime("%H:%M") %></td>
    <td><%= fixture.home_team %></td>
    <td><%= fixture.away_team %></td>
    <td><%= link_to 'Show', fixture %></td>
    <td><%= link_to 'Edit', edit_fixture_path(fixture) %></td>
    <td><%= link_to 'Destroy', fixture, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fixture', new_fixture_path %>

app/views/fixtures/new.html.erb
<h1>Fixture Administration</h1>

<%= render 'form' %>

<%= link_to 'Back', fixtures_path %>

app/views/fixtures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @fixture.date %>
</p>

<p>
  <b>Home team:</b>
  <%= @fixture.home_team %>
</p>

<p>
  <b>Away team:</b>
  <%= @fixture.away_team %>
</p>


<%= link_to 'Edit', edit_fixture_path(@fixture) %> |
<%= link_to 'Back', fixtures_path %>

app/views/layouts/_header.html.erb
<header>
    <%= image_tag("epl.png", :alt => "Logo", :class => "round") %>
    <nav class="round">
      <ul>
        <li><%= link_to "Home", '#' %></li>
		<li><%= link_to "Users", '#' %></li>
		<li><%= link_to "Teams", '#' %></li>
		<li><%= link_to "Fixtures", '#' %></li>
        <li><%= link_to "Gameweeks", '#' %></li>
		<li><%= link_to "Selections", '#' %></li>
		<li><%= link_to "Leagues", '#' %></li>
        <li><%= link_to "Sign in", '#' %></li>
      </ul>
    </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->    
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>  
	<title>English Premier League Predictor Game</title>  
	<%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
</head>
<body>
<div class="container">
  <%= render 'layouts/header' %>
  <section class="round">
    <%= yield %>
  </section>
</div>
</body>
</html>

app/views/pages/contact.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Premier League Predictor | Contact</title>
  </head>
  <body>
    <h1>Contact</h1>
    <p>
      Got some feedback for the application?
      <a href="mailto:John.McFeely@invisionwfm.com?subject=Premier League Predictor">
	  <br>Contact Me</a>
    </p>
  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Premier League Predictor | Home</title>
  </head>
  <body>
    <h1>Predictor Home Page</h1>
    <p>
      Welcome to the beta version of the English Premier League Predictor Game where each week you are asked to 
	  predict the result of each of the Premier League fixtures for that gameweek. Aswell as predicting the result (HOME/DRAW/AWAY) they
	  are also asked to rank them numerically from 10-1 based on your expectations, with 10 for the prediction you are most confident in 
	  being correct, and 1 with the prediction your are least confident in being correct.
    </p>
	<p>
	  We are initially only accepting 50 users as means of keeping the score reporting trackable and manageable so please sign up
	  now for your chance to join the fun. Please click the Sign Up button below !!
	</p>
	<%= link_to "Sign up now!", '#', :class => "signup_button round" %>

  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users Administration</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>